version: "3.0"
services:

  api:
    container_name: api-payara
    image: payara/micro:5.2021.10-jdk11
    build: 
      context: ./dockerfile
      dockerfile: payara.dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./api/target/api-0.0.1.war:/opt/payara/deployments/api-0.0.1.war
    environment:
      - JVM_ARGS=-Xmx4096m -Xms2048m
    networks:
      - api-net
    depends_on:
      - postgres-db

  postgres-db:
    container_name: api-postgres
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/api-database:/var/lib/postgresql/data
      - ./sql-schema/database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks:
      - api-net
      
  pgadmin:
    container_name: api-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    networks:
      - api-net
    depends_on:
      - postgres-db

  app:
    image: node:23
    container_name: bids-app
    working_dir: /usr/src/app
    volumes:
      - ./bids-app:/usr/src/app
    ports:
      - "8000:3000"
    networks:
      - api-net
    command: >
      sh -c "npm install && npm start"
    depends_on:
      - api


networks:
  api-net:
    driver: bridge
    
